# Generated by Django 5.2.7 on 2026-01-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_add_merchant_withdrawal_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='bvn',
            field=models.CharField(blank=True, help_text='Bank Verification Number', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth for KYC', null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Male'), ('1', 'Female')], help_text='Gender (0: Male, 1: Female)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='psb_wallet_account',
            field=models.CharField(blank=True, help_text='9PSB Wallet Account Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='psb_wallet_created_at',
            field=models.DateTimeField(blank=True, help_text='When 9PSB wallet was created', null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='psb_wallet_name',
            field=models.CharField(blank=True, help_text='9PSB Wallet Account Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='psb_wallet_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], help_text='9PSB Wallet Status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='psb_wallet_tier',
            field=models.CharField(blank=True, help_text='9PSB Wallet Tier (1, 2, or 3)', max_length=10, null=True),
        ),
    ]
