# Generated by Django 5.2.7 on 2026-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_add_wallet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='ac_no',
            field=models.CharField(blank=True, help_text='Account number for merchant', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gl_no',
            field=models.CharField(blank=True, help_text='GL number for merchant account', max_length=10, null=True),
        ),
    ]
