# Generated by Django 5.2.7 on 2026-02-02 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_add_is_parent_branch'),
        ('merchant', '0004_add_merchant_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchanttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('customer_registration', 'Customer Registration'), ('deposit', 'Customer Deposit'), ('withdrawal', 'Customer Withdrawal'), ('transfer_in', 'FinanceFlex Transfer In'), ('transfer_out', 'Transfer Out'), ('bill_payment', 'Bill Payment'), ('airtime', 'Airtime Purchase'), ('data', 'Data Purchase'), ('float_topup', 'Float Top-up'), ('commission', 'Commission'), ('nin_verification', 'NIN Verification')], max_length=30),
        ),
        migrations.CreateModel(
            name='MerchantChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='merchant.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Chat Conversation',
                'verbose_name_plural': 'Merchant Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField()),
                ('is_from_merchant', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin who sent this message (if not from merchant)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='merchant.merchantchatconversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('alert', 'Alert'), ('promo', 'Promotion'), ('update', 'System Update')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_notifications', to='company.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, help_text='Leave empty to send to all merchants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='merchant.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Notification',
                'verbose_name_plural': 'Merchant Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NINVerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable NIN verification service')),
                ('charge_amount', models.DecimalField(decimal_places=2, default=200.0, help_text='Amount to charge merchant per NIN verification', max_digits=10)),
                ('income_gl_no', models.CharField(blank=True, help_text='GL number for income account (where charges go)', max_length=20, null=True)),
                ('income_ac_no', models.CharField(blank=True, help_text='Account number for income (where charges go)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nin_verification_config', to='company.branch')),
            ],
            options={
                'verbose_name': 'NIN Verification Config',
                'verbose_name_plural': 'NIN Verification Configs',
            },
        ),
        migrations.CreateModel(
            name='MerchantNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='merchant.merchant')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='merchant.merchantnotification')),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('notification', 'merchant')},
            },
        ),
    ]
