# Generated by Django 5.2.8 on 2025-12-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_gl_no', models.CharField(max_length=20)),
                ('cust_ac_no', models.CharField(max_length=20)),
                ('fixed_gl_no', models.CharField(max_length=20)),
                ('fixed_ac_no', models.CharField(max_length=20)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('fixed_int_gl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('fixed_int_ac_no', models.CharField(blank=True, max_length=20, null=True)),
                ('interest_option', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-monthly', 'Every 2 Months'), ('quarterly', 'Every 3 Months'), ('4-months', 'Every 4 Months'), ('yearly', 'Yearly'), ('end', 'At Maturity')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('maturity_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDepositHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_gl_no', models.CharField(max_length=20)),
                ('fixed_ac_no', models.CharField(max_length=20)),
                ('trx_date', models.DateField()),
                ('trx_type', models.CharField(max_length=50)),
                ('trx_naration', models.TextField()),
                ('trx_no', models.CharField(max_length=50, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_history', to='company.branch')),
            ],
        ),
    ]
