# Generated by Django 5.1.4 on 2025-03-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('customers', '0005_fixeddepositaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_ac_no', models.CharField(max_length=20, unique=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_option', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-monthly', 'Every 2 Months'), ('quarterly', 'Every 3 Months'), ('4-months', 'Every 4 Months'), ('yearly', 'Yearly'), ('end', 'At Maturity')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.customer')),
            ],
        ),
    ]
