# Generated by Django 5.1.4 on 2025-03-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_fixeddepositaccount'),
        ('fixed_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.fixeddepositaccount'),
        ),
    ]
