# Generated by Django 5.1.4 on 2025-03-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('customers', '0005_fixeddepositaccount'),
        ('fixed_deposit', '0002_alter_fixeddeposit_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='cust_ac_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='cust_gl_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='fixed_gl_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_gl_accounts', to='accounts_admin.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.customer'),
        ),
    ]
