# Generated by Django 5.1.4 on 2025-03-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_fixeddepositaccount'),
        ('fixed_deposit', '0004_alter_fixeddeposit_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='customer_fixed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.fixeddepositaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_accounts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_ac_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_gl_no',
            field=models.CharField(max_length=20),
        ),
    ]
