# Generated by Django 5.1.4 on 2025-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0005_fixeddeposit_customer_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
