# Generated by Django 5.1.4 on 2025-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0006_fixeddeposit_interest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='customer_fixed',
        ),
    ]
