# Generated by Django 5.1.4 on 2025-03-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('fixed_deposit', '0007_remove_fixeddeposit_customer_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDepositHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_gl_no', models.CharField(max_length=20)),
                ('fixed_ac_no', models.CharField(max_length=20)),
                ('trx_date', models.DateField()),
                ('trx_type', models.CharField(max_length=50)),
                ('trx_naration', models.TextField()),
                ('trx_no', models.CharField(max_length=50, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposit_history', to='company.branch')),
            ],
        ),
    ]
