# Generated by Django 5.1.4 on 2025-03-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0008_account_fixed_dep_int_ac_no_and_more'),
        ('fixed_deposit', '0008_fixeddeposithist'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='fixed_int_ac_no',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_int_ac', to='accounts_admin.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='fixed_int_gl_no',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_int_gl', to='accounts_admin.account'),
            preserve_default=False,
        ),
    ]
