# Generated by Django 5.1.4 on 2025-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0009_fixeddeposit_fixed_int_ac_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_int_ac_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_int_gl_no',
            field=models.CharField(max_length=20),
        ),
    ]
