# Generated by Django 5.1.4 on 2025-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0010_alter_fixeddeposit_fixed_int_ac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_int_ac_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='fixed_int_gl_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
