# Generated by Django 5.1.4 on 2026-01-12 23:28

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    import uuid as uuid_module
    for model_name in ['FixedDeposit', 'FixedDepositHist']:
        Model = apps.get_model('fixed_deposit', model_name)
        for obj in Model.objects.all():
            obj.uuid = uuid_module.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0011_fixeddeposit_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposithist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposithist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
