# Generated by Django 5.1.4 on 2026-01-13 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_branch_max_customers'),
        ('fixed_deposit', '0012_fixeddeposit_uuid_fixeddeposithist_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixeddeposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fixed Deposit', 'verbose_name_plural': 'Fixed Deposits'},
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest accrued till date', max_digits=15),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='certificate_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='compound_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='quarterly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total interest already paid out', max_digits=15),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest_type',
            field=models.CharField(choices=[('simple', 'Simple Interest'), ('compound', 'Compound Interest')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='is_lien_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='is_senior_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='last_interest_calc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='lien_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='lien_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='lien_reference',
            field=models.CharField(blank=True, help_text='Loan reference number if lien is marked', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='original_fd',
            field=models.ForeignKey(blank=True, help_text='Reference to original FD if renewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_fds', to='fixed_deposit.fixeddeposit'),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='premature_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Penalty rate % for early withdrawal', max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='senior_citizen_extra_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tds_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tds_deducted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='interest_option',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-monthly', 'Every 2 Months'), ('quarterly', 'Every 3 Months'), ('4-months', 'Every 4 Months'), ('yearly', 'Yearly'), ('end', 'At Maturity')], default='end', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('closed', 'Closed'), ('premature_closed', 'Premature Closed'), ('renewed', 'Renewed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='FDProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_tenure_months', models.IntegerField(default=1)),
                ('max_tenure_months', models.IntegerField(default=60)),
                ('base_interest_rate', models.DecimalField(decimal_places=2, help_text='Base interest rate %', max_digits=5)),
                ('senior_citizen_extra_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Extra rate for senior citizens %', max_digits=5)),
                ('interest_type', models.CharField(choices=[('simple', 'Simple Interest'), ('compound', 'Compound Interest')], default='simple', max_length=20)),
                ('compound_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='quarterly', max_length=20, null=True)),
                ('allow_premature_withdrawal', models.BooleanField(default=True)),
                ('premature_penalty_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Penalty rate % on interest for early withdrawal', max_digits=5)),
                ('min_lock_in_days', models.IntegerField(default=7, help_text='Minimum days before premature withdrawal allowed')),
                ('allow_auto_renewal', models.BooleanField(default=True)),
                ('tds_applicable', models.BooleanField(default=True)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='TDS rate % on interest', max_digits=5)),
                ('tds_threshold', models.DecimalField(decimal_places=2, default=40000.0, help_text='TDS applicable if interest exceeds this amount per year', max_digits=15)),
                ('allow_loan_against_fd', models.BooleanField(default=True)),
                ('max_loan_percentage', models.DecimalField(decimal_places=2, default=90.0, help_text='Max % of FD that can be given as loan', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fd_products', to='company.branch')),
            ],
            options={
                'verbose_name': 'FD Product',
                'verbose_name_plural': 'FD Products',
            },
        ),
        migrations.CreateModel(
            name='FDInterestSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_tenure', models.IntegerField()),
                ('max_tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_slabs', to='fixed_deposit.fdproduct')),
            ],
            options={
                'verbose_name': 'FD Interest Slab',
                'verbose_name_plural': 'FD Interest Slabs',
                'ordering': ['min_amount', 'min_tenure'],
            },
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='fd_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_deposits', to='fixed_deposit.fdproduct'),
        ),
        migrations.CreateModel(
            name='FDRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('renewal_date', models.DateField()),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_earned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('renewal_type', models.CharField(choices=[('principal_only', 'Principal Only'), ('principal_interest', 'Principal + Interest'), ('custom', 'Custom Amount')], default='principal_interest', max_length=20)),
                ('renewed_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_tenure_months', models.IntegerField()),
                ('new_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_auto_renewal', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('original_fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='fixed_deposit.fixeddeposit')),
                ('renewed_fd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewed_from', to='fixed_deposit.fixeddeposit')),
            ],
            options={
                'verbose_name': 'FD Renewal History',
                'verbose_name_plural': 'FD Renewal Histories',
                'ordering': ['-renewal_date'],
            },
        ),
        migrations.CreateModel(
            name='FDInterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accrual_date', models.DateField()),
                ('opening_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_in_period', models.IntegerField(default=1)),
                ('accrued_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cumulative_accrued', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_trx_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('fixed_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='fixed_deposit.fixeddeposit')),
            ],
            options={
                'verbose_name': 'FD Interest Accrual',
                'verbose_name_plural': 'FD Interest Accruals',
                'ordering': ['-accrual_date'],
                'unique_together': {('fixed_deposit', 'accrual_date')},
            },
        ),
    ]
