"""
Django settings for profit_solutions project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
import os

env = environ.Env()
environ.Env.read_env()  # loads .env file



from dotenv import load_dotenv

load_dotenv()  # loads .env automatically

PSB_BASE_URL = os.getenv("PSB_BASE_URL", "https://baastest.9psb.com.ng/iva-api/v1").strip()
PSB_PUBLIC_KEY = os.getenv("PSB_PUBLIC_KEY", "").strip()
PSB_PRIVATE_KEY = os.getenv("PSB_PRIVATE_KEY", "").strip()


NINEPSB_API_BASE = os.getenv("NINEPSB_API_BASE", "http://102.216.128.75:9090/waas/api/v1").strip()
NINEPSB_USERNAME = os.getenv("NINEPSB_USERNAME", "").strip()
NINEPSB_PASSWORD = os.getenv("NINEPSB_PASSWORD", "").strip()
NINEPSB_CLIENT_ID = os.getenv("NINEPSB_CLIENT_ID", "").strip()
NINEPSB_CLIENT_SECRET = os.getenv("NINEPSB_CLIENT_SECRET", "").strip()
NINEPSB_API_TIMEOUT = 30


PSB_ENABLED = True
PSB_CURRENCY = "NGN"
PSB_COUNTRY = "NGA"


# PSB_BASE_URL = os.getenv("PSB_BASE_URL", "https://baastest.9psb.com.ng/ipaymw-api/v1")
# PSB_IVA_BASE_URL = os.getenv("PSB_IVA_BASE_URL", "https://baastest.9psb.com.ng/iva-api/v1")
# PSB_PUBLIC_KEY = os.getenv("PSB_PUBLIC_KEY")
# PSB_PRIVATE_KEY = os.getenv("PSB_PRIVATE_KEY")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%f1%grgx3u=j1#pklxrabzx$eas@ao=$^wh)s#f83zq9^&sp-%'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# PRODUCTION
# ALLOWED_HOSTS = ['104.248.251.250','financeflex.sitanetorbit.com']

# LOCAL
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'company',
    'accounts',
    'accounts_admin',
   
    'customers',
    'transactions',
    'loans',
    'django.contrib.humanize',
    'reports',
    'end_of_periods',
    'fixed_assets',
    'fixed_deposit',
    # 'audit_trail',
    'rest_framework',
    'rest_framework_simplejwt',
    'api',
    'django_filters',
    'corsheaders',
    'ninepsb',
    'adverts',
   
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'audit_trail.middleware.AuditMiddleware',
    'corsheaders.middleware.CorsMiddleware',
  

]




# Allows any port on localhost for CORS
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(:\d+)?$",
    r"^http://127\.0\.0\.1(:\d+)?$",
]


ROOT_URLCONF = 'profit_solutions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.soon_to_expire'
            ],
        },
    },
]

WSGI_APPLICATION = 'profit_solutions.wsgi.application'



# settings.py
# settings.py
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'MFB',
#         'USER': 'postgres',
#         'PASSWORD': 'People',
#         'HOST': 'localhost',
#         # 'HOST': 'database-2.cxwm64gcozpx.us-west-2.rds.amazonaws.com',  # Or your database host
#         'PORT': '5432',           # Leave empty for the default PostgreSQL port (5432)
#     }
# }




# LOCAL DATABASE
import os

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# PRODUCTION DATABASE
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'demo_db',
#         'USER': 'demo_user',
#         'PASSWORD': 'Completed@1234',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',  # default: all views require auth
#     ),
# }




REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # safer default
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Optional keep Session for admin/browsable API:
        # "rest_framework.authentication.SessionAuthentication",
        # Optional during local dev only:
        # "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:XXXXX",
    "http://127.0.0.1:XXXXX",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:XXXXX",
    "http://127.0.0.1:XXXXX",
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# This is where collectstatic will gather all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# This tells Django to look in your project-level static/ folder (next to manage.py)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'  # Example for a custom user model



# =====================
# 📧 EMAIL CONFIG
# =====================
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.zoho.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

# =====================
# 📱 SMS CONFIG (Termii)
# =====================
TERMII_API_KEY = env("TERMII_API_KEY")
TERMII_SENDER_ID = env("TERMII_SENDER_ID", default="FinanceFlex")
TERMII_SMS_URL = env("TERMII_SMS_URL", default="https://api.ng.termii.com/api/sms/send")
SMS_DELIVERY_WEBHOOK_URL = env("SMS_DELIVERY_WEBHOOK_URL", default=None)








# CACHE CONFIGURATION (Required for OTP storage)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# CORS CONFIGURATION (for Flutter app)
CORS_ALLOW_ALL_ORIGINS = True  # For development
CORS_ALLOW_CREDENTIALS = True


