# Generated by Django 5.2.7 on 2025-10-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the beneficiary.', max_length=100)),
                ('bank_name', models.CharField(help_text='Bank name of the beneficiary.', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number.', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number.', max_length=15, null=True)),
                ('nickname', models.CharField(blank=True, help_text='Nickname for quick reference.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this beneficiary.', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['name'],
                'unique_together': {('user', 'account_number')},
            },
        ),
    ]
