# Generated by Django 5.2.7 on 2025-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('attempts', models.IntegerField(default=0)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_verification',
                'indexes': [models.Index(fields=['account_number', 'created_at'], name='otp_verific_account_f0b79d_idx'), models.Index(fields=['expires_at'], name='otp_verific_expires_b46ee7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.IntegerField()),
                ('verified_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'registration_token',
                'indexes': [models.Index(fields=['token'], name='registratio_token_25b9be_idx'), models.Index(fields=['expires_at'], name='registratio_expires_fca87b_idx')],
            },
        ),
    ]
