# Generated by Django 5.2.7 on 2025-11-13 12:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otpverification_registrationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTransferFeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other Bank Transfer Fee', max_length=100)),
                ('transfer_type', models.CharField(choices=[('other_bank', 'Transfer to Other Bank'), ('international', 'International Transfer')], default='other_bank', max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Base fee charged to ALL customers for other bank transfers', max_digits=10)),
                ('free_transfers_per_day', models.IntegerField(default=3, help_text='Number of free transfers allowed per customer per day')),
                ('free_transfers_per_month', models.IntegerField(default=10, help_text='Number of free transfers allowed per customer per month')),
                ('fee_gl_no', models.CharField(help_text='GL number where ALL customer fees are credited', max_length=10)),
                ('fee_ac_no', models.CharField(help_text='Account number where ALL customer fees are credited', max_length=20)),
                ('min_amount_for_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum transfer amount to charge fee (applies to ALL customers)', max_digits=10)),
                ('max_daily_free_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Maximum daily amount for free transfers per customer', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE configuration can be active at a time')),
                ('effective_date', models.DateTimeField(auto_now_add=True, help_text='When this configuration becomes effective')),
                ('created_by', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Transfer Fee Configuration',
                'verbose_name_plural': 'Global Transfer Fee Configurations',
                'db_table': 'global_transfer_fee_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransferUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('daily_transfer_count', models.IntegerField(default=0)),
                ('daily_transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('daily_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monthly_transfer_count', models.IntegerField(default=0)),
                ('monthly_transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monthly_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_transfer_usage',
                'indexes': [models.Index(fields=['customer_id', 'date'], name='customer_tr_custome_654e80_idx'), models.Index(fields=['customer_id', 'month'], name='customer_tr_custome_2a0ca0_idx')],
                'unique_together': {('customer_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GlobalTransferFeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50)),
                ('customer_account', models.CharField(max_length=20)),
                ('transfer_reference', models.CharField(db_index=True, max_length=100)),
                ('fee_config_name', models.CharField(max_length=100)),
                ('base_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('was_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.CharField(blank=True, max_length=200)),
                ('free_transfers_remaining_daily', models.IntegerField(default=0)),
                ('free_transfers_remaining_monthly', models.IntegerField(default=0)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_debited', models.DecimalField(decimal_places=2, max_digits=15)),
                ('destination_bank', models.CharField(max_length=10)),
                ('destination_account', models.CharField(max_length=20)),
                ('destination_name', models.CharField(blank=True, max_length=100)),
                ('fee_gl_no', models.CharField(max_length=10)),
                ('fee_ac_no', models.CharField(max_length=20)),
                ('customer_gl_no', models.CharField(max_length=10)),
                ('customer_ac_no', models.CharField(max_length=20)),
                ('fee_transaction_ref', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transfer Fee Transaction (All Customers)',
                'verbose_name_plural': 'Transfer Fee Transactions (All Customers)',
                'db_table': 'global_transfer_fee_transactions',
                'indexes': [models.Index(fields=['customer_id', 'processed_at'], name='global_tran_custome_f30393_idx'), models.Index(fields=['transfer_reference'], name='global_tran_transfe_00f4fc_idx'), models.Index(fields=['processing_date'], name='global_tran_process_6e8566_idx'), models.Index(fields=['was_waived'], name='global_tran_was_wai_c757b1_idx')],
            },
        ),
    ]
