# Generated by Django 5.2.7 on 2025-11-18 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globaltransferfeeconfiguration_customertransferusage_and_more'),
        ('customers', '0022_customer_bank_code_customer_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vas_bills_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VASCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('AIRTIME', 'Airtime Top-up'), ('DATA', 'Data Purchase'), ('ELECTRICITY', 'Electricity Bill'), ('CABLE_TV', 'Cable TV'), ('INTERNET', 'Internet Bill'), ('WATER', 'Water Bill'), ('BETTING', 'Betting/Gaming'), ('INSURANCE', 'Insurance Premium')], max_length=20, unique=True)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximum_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vas_charges',
            },
        ),
        migrations.CreateModel(
            name='VASProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vas_providers',
            },
        ),
        migrations.CreateModel(
            name='VASTokenCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vas_token_cache',
            },
        ),
        migrations.CreateModel(
            name='BillsBiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('api_identifier', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charges', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billers', to='api.billscategory')),
            ],
            options={
                'db_table': 'vas_bills_billers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('validity', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_type', models.CharField(choices=[('HOT', 'Hot Deals'), ('DAILY', 'Daily Plans'), ('WEEKLY', 'Weekly Plans'), ('MONTHLY', 'Monthly Plans'), ('XTRAVALUE', 'XtraValue Plans')], default='MONTHLY', max_length=20)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('bonus_description', models.CharField(blank=True, max_length=100)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_plans', to='api.vasprovider')),
            ],
            options={
                'db_table': 'vas_data_plans',
                'unique_together': {('provider', 'plan_id')},
            },
        ),
        migrations.CreateModel(
            name='VASTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('AIRTIME', 'Airtime Top-up'), ('DATA', 'Data Purchase'), ('ELECTRICITY', 'Electricity Bill'), ('CABLE_TV', 'Cable TV'), ('INTERNET', 'Internet Bill'), ('WATER', 'Water Bill'), ('BETTING', 'Betting/Gaming'), ('INSURANCE', 'Insurance Premium')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('data_bundle', models.CharField(blank=True, max_length=50)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('debit_account', models.CharField(blank=True, max_length=20)),
                ('memtrans_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vas_transactions', to='customers.customer')),
                ('data_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dataplan')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vasprovider')),
            ],
            options={
                'db_table': 'vas_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
