# Generated by Django 5.1.4 on 2025-01-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.IntegerField(unique=True),
        ),
    ]
