# Generated by Django 5.2.8 on 2025-12-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('profile_picture', models.ImageField(default='images/avatar.jpg', upload_to='users/profile_pictures')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'System Administration'), (2, 'General Manager'), (3, 'Branch Manager'), (4, 'Assistant Manager'), (5, 'Accountant'), (6, 'Accounts Assistant'), (7, 'Credit Supervisor'), (8, 'Credit Officer'), (9, 'Verification Officer'), (10, 'Customer Service Unit'), (11, 'Teller'), (12, 'Management Information System'), (13, 'Customer')], null=True)),
                ('branch', models.CharField(help_text='Vendor DB Branch ID', max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('last_otp_sent', models.DateTimeField(blank=True, null=True)),
                ('cashier_gl', models.CharField(blank=True, max_length=6, null=True)),
                ('cashier_ac', models.CharField(blank=True, max_length=1, null=True)),
                ('activation_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('transaction_pin', models.CharField(blank=True, help_text='Securely hashed 4–6 digit transaction PIN', max_length=128, null=True)),
                ('gl_no', models.CharField(blank=True, help_text='General Ledger number linked to this user (Customer or Teller).', max_length=20, null=True)),
                ('ac_no', models.CharField(blank=True, help_text='Account number linked to this user (Customer or Teller).', max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('function_used', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['user', 'date_time'], name='accounts_us_user_id_eb41a8_idx'), models.Index(fields=['function_used'], name='accounts_us_functio_423c09_idx')],
            },
        ),
    ]
