# Generated by Django 5.1.4 on 2025-01-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0002_remove_company_branch_code_and_more'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Clents',
        #     new_name='Clients',
        # ),  # Commented out - model already named Clients in regenerated 0001_initial
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'System Administration'), (2, 'General Manager'), (3, 'Branch Manager'), (4, 'Assistant Manager'), (5, 'Accountant'), (6, 'Accounts Assistant'), (7, 'Credit Supervisor'), (8, 'Credit Officer'), (9, 'Verification Officer'), (10, 'Customer Service Unit'), (11, 'Teller'), (12, 'Management Information System')], null=True),
        ),
    ]
