# Generated by Django 5.1.4 on 2025-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_otp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'System Administration'), (2, 'General Manager'), (3, 'Branch Manager'), (4, 'Assistant Manager'), (5, 'Accountant'), (6, 'Accounts Assistant'), (7, 'Credit Supervisor'), (8, 'Credit Officer'), (9, 'Verification Officer'), (10, 'Customer Service Unit'), (11, 'Teller'), (12, 'Management Information System'), (13, 'Customer')], null=True),
        ),
    ]
