# Generated by Django 5.2.7 on 2025-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Securely hashed 4–6 digit transaction PIN', max_length=128, null=True),
        ),
    ]
