# Generated by Django 5.2.7 on 2025-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ac_no',
            field=models.CharField(blank=True, help_text='Account number linked to this user (Customer or Teller).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gl_no',
            field=models.CharField(blank=True, help_text='General Ledger number linked to this user (Customer or Teller).', max_length=20, null=True),
        ),
    ]
