# Generated by Django 5.2.8 on 2025-12-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_ac_no_user_gl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
