# Generated by Django 5.2.8 on 2025-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_ac_no_user_gl_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-date_time']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.CharField(blank=True, help_text='Branch ID from vendor database', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'date_time'], name='accounts_us_user_id_eb41a8_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['function_used'], name='accounts_us_functio_423c09_idx'),
        ),
    ]
