# Generated by Django 5.2.8 on 2025-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_useractivitylog_options_remove_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch_id',
            field=models.CharField(default=1, help_text='Branch ID from vendor database - REQUIRED for all users', max_length=10),
            preserve_default=False,
        ),
    ]
