# Generated by Django 5.1.4 on 2026-01-12 23:28

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing records"""
    import uuid as uuid_module
    
    # Get models
    Clients = apps.get_model('accounts', 'Clients')
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    UserActivityLog = apps.get_model('accounts', 'UserActivityLog')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Update each record with unique UUID
    for model in [Clients, Role, User, UserActivityLog, UserProfile]:
        for obj in model.objects.all():
            obj.uuid = uuid_module.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        # Step 1: Add UUID fields without unique constraint
        migrations.AddField(
            model_name='clients',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.CharField(blank=True, db_column='branch_id', help_text='Vendor DB Branch ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        # Step 3: Make UUID fields unique and non-null
        migrations.AlterField(
            model_name='clients',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
