# Generated by Django 5.2.8 on 2025-12-03 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('customers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(max_length=6, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glno_debit_account', models.CharField(max_length=6)),
                ('acno_debit_account', models.CharField(max_length=1)),
                ('ses_date', models.DateField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestRate', to='company.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Memtrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loans', models.CharField(blank=True, max_length=30, null=True)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('trx_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ses_date', models.DateField()),
                ('app_date', models.DateField(blank=True, null=True)),
                ('sys_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.CharField(blank=True, default='A', max_length=10, null=True)),
                ('type', models.CharField(blank=True, default='N', max_length=10, null=True)),
                ('account_type', models.CharField(blank=True, default='N', max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('trx_type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memtrans_branch', to='company.branch')),
                ('cust_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_branch', to='company.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('trx_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ses_date', models.DateField()),
                ('app_date', models.DateField(blank=True, null=True)),
                ('sys_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], default='DEPOSIT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('customer_pin_verified', models.BooleanField(default=False)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('location_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_branch', to='company.branch')),
                ('cust_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_cust_branch', to='company.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'trx_type'], name='transaction_status_f16061_idx'), models.Index(fields=['initiated_by', 'created_at'], name='transaction_initiat_a7387c_idx'), models.Index(fields=['gl_no', 'ac_no'], name='transaction_gl_no_e5edfd_idx'), models.Index(fields=['trx_no'], name='transaction_trx_no_e2c75b_idx')],
            },
        ),
    ]
