# Generated by Django 5.1.4 on 2025-01-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_branch_branch_code'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestRate', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memtrans', to='company.branch'),
        ),
    ]
