# Generated by Django 5.1.4 on 2025-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_interestrate_branch_alter_memtrans_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='memtrans',
            name='cust_branch',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
