# Generated by Django 5.1.4 on 2025-01-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('transactions', '0003_memtrans_cust_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_memtrans', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='cust_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_branch_memtrans', to='company.branch'),
        ),
    ]
