# Generated by Django 5.1.4 on 2025-01-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_unique_name_combination_and_more'),
        ('transactions', '0004_alter_memtrans_branch_alter_memtrans_cust_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='cust_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_branch_customers', to='customers.customer'),
        ),
    ]
