# Generated by Django 5.1.4 on 2025-01-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('transactions', '0005_alter_memtrans_cust_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memtrans',
            name='cust_branch',
        ),
        migrations.AddField(
            model_name='memtrans',
            name='ust_branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
            preserve_default=False,
        ),
    ]
