# Generated by Django 5.1.4 on 2025-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_memtrans_cust_branch_memtrans_ust_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memtrans',
            old_name='ust_branch',
            new_name='cust_branch',
        ),
    ]
