# Generated by Django 5.1.4 on 2025-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_ust_branch_memtrans_cust_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='cust_branch',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
