# Generated by Django 5.1.4 on 2025-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_memtrans_cust_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='trx_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
