# Generated by Django 5.1.4 on 2025-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_memtrans_trx_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
