# Generated by Django 5.1.4 on 2025-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_memtrans_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
