# Generated by Django 5.1.4 on 2025-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_memtrans_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='trx_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
