# Generated by Django 5.1.4 on 2025-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_memtrans_trx_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
