# Generated by Django 5.1.4 on 2025-03-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_last_notification_date'),
        ('transactions', '0016_alter_memtrans_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memtrans_branch', to='company.branch'),
        ),
    ]
