# Generated by Django 5.1.4 on 2025-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_memtrans_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='memtrans',
            name='trx_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
