# Generated by Django 5.1.4 on 2025-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_memtrans_trx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memtrans',
            name='account_type',
            field=models.CharField(blank=True, default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='type',
            field=models.CharField(blank=True, default='N', max_length=10, null=True),
        ),
    ]
