# Generated by Django 5.1.4 on 2026-01-12 23:28

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    import uuid as uuid_module
    for model_name in ['InterestRate', 'MemTrans', 'PendingTransaction']:
        Model = apps.get_model('transactions', model_name)
        for obj in Model.objects.all():
            obj.uuid = uuid_module.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_memtrans_account_type_alter_memtrans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='memtrans',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='interestrate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memtrans',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
