# Generated by Django 5.2.7 on 2025-11-17 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_mobile_teller_ac_no_and_more'),
        ('customers', '0022_customer_bank_code_customer_bank_name'),
        ('transactions', '0019_alter_memtrans_account_type_alter_memtrans_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('trx_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ses_date', models.DateField()),
                ('app_date', models.DateField(blank=True, null=True)),
                ('sys_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], default='DEPOSIT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('customer_pin_verified', models.BooleanField(default=False)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('location_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_branch', to='company.branch')),
                ('cust_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_cust_branch', to='company.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'trx_type'], name='transaction_status_f16061_idx'), models.Index(fields=['initiated_by', 'created_at'], name='transaction_initiat_a7387c_idx'), models.Index(fields=['gl_no', 'ac_no'], name='transaction_gl_no_e5edfd_idx'), models.Index(fields=['trx_no'], name='transaction_trx_no_e2c75b_idx')],
            },
        ),
    ]
