# Generated by Django 5.1.4 on 2025-01-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/avatar.jpg', upload_to='photo/customer')),
                ('sign', models.ImageField(default='images/avatar.jpg', upload_to='sign/customer')),
                ('branch', models.CharField(blank=True, max_length=8, null=True)),
                ('gl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cust_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'WIDOW')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('internal', models.BooleanField(blank=True, default=False, null=True)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Dormant'), ('P', 'Pending')], max_length=1, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('label', models.CharField(blank=True, max_length=1, null=True)),
                ('loan', models.CharField(blank=True, default='F', max_length=1, null=True)),
                ('sms', models.BooleanField(default=False)),
                ('credit_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.account_officer')),
                ('cust_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.category')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.id_card_type')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'gl_no'), name='unique_name_combination'), models.UniqueConstraint(fields=('gl_no', 'ac_no'), name='unique_gl_ac_combination')],
            },
        ),
    ]
