# Generated by Django 5.2.8 on 2025-12-03 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_admin', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_code', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/avatar.jpg', upload_to='photo/customer')),
                ('sign', models.ImageField(default='images/avatar.jpg', upload_to='sign/customer')),
                ('gl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cust_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('internal', models.BooleanField(blank=True, default=False, null=True)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('D', 'Dormant'), ('P', 'Pending')], max_length=1, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('label', models.CharField(blank=True, max_length=1, null=True)),
                ('loan', models.CharField(blank=True, default='F', max_length=1, null=True)),
                ('sms', models.BooleanField(default=False)),
                ('email_alert', models.BooleanField(default=True)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('nin', models.CharField(blank=True, max_length=16, null=True)),
                ('wallet_account', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_limit', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum transfer limit in Naira.', max_digits=12, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_registered', models.DateField(auto_now_add=True, null=True)),
                ('is_company', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='company.branch')),
                ('credit_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.account_officer')),
                ('cust_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.category')),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.id_card_type')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.region')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='customers.group')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_gl_no', models.CharField(max_length=20, unique=True)),
                ('fixed_ac_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('PROOF_OF_ADDRESS', 'Proof of Address')], max_length=20)),
                ('file', models.FileField(upload_to='kyc_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, help_text='Username of verifying user', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gl_no', models.CharField(max_length=5)),
                ('ac_no', models.CharField(max_length=5)),
                ('card_number', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_cards', to='customers.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'gl_no', 'branch'), name='unique_name_combination'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('gl_no', 'ac_no', 'branch'), name='unique_gl_ac_branch_combination'),
        ),
        migrations.AddConstraint(
            model_name='virtualcard',
            constraint=models.UniqueConstraint(fields=('gl_no', 'ac_no'), name='uniq_virtual_card_gl_ac'),
        ),
    ]
