# Generated by Django 5.1.4 on 2025-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('company', '0005_alter_branch_branch_code'),
        ('customers', '0002_alter_customer_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_gl_ac_combination',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('gl_no', 'ac_no', 'branch'), name='unique_gl_ac_branch_combination'),
        ),
    ]
