# Generated by Django 5.1.4 on 2025-01-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('company', '0005_alter_branch_branch_code'),
        ('customers', '0003_remove_customer_unique_gl_ac_combination_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_name_combination',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'gl_no', 'branch'), name='unique_name_combination'),
        ),
    ]
