# Generated by Django 5.1.4 on 2025-03-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('customers', '0004_remove_customer_unique_name_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_ac_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
