# Generated by Django 5.1.4 on 2025-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_fixeddepositaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddepositaccount',
            name='fixed_gl_no',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
