# Generated by Django 5.1.4 on 2025-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_fixeddepositaccount_fixed_gl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow')], max_length=1, null=True),
        ),
    ]
