# Generated by Django 5.1.4 on 2025-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_alert',
            field=models.BooleanField(default=True),
        ),
    ]
