# Generated by Django 5.1.4 on 2025-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_contact_person_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_code', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
