# Generated by Django 5.1.4 on 2025-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_kycdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
