# Generated by Django 5.1.4 on 2025-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_wallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nin',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
