# Generated by Django 5.1.4 on 2025-10-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_bvn_customer_nin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='wallet_number',
            new_name='wallet_account',
        ),
    ]
