# Generated by Django 5.1.4 on 2025-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_rename_wallet_number_customer_wallet_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transfer_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum transfer limit in Naira.', max_digits=12, null=True),
        ),
    ]
