# Generated by Django 5.2.7 on 2025-10-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customer_transfer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Securely hashed 4–6 digit transaction PIN', max_length=128, null=True),
        ),
    ]
