# Generated by Django 5.2.7 on 2025-10-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customer_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transaction_pin',
        ),
    ]
