# Generated by Django 5.2.7 on 2025-10-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_virtualcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualcard',
            name='card_name',
        ),
    ]
