# Generated by Django 5.2.7 on 2025-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_remove_virtualcard_card_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualcard',
            options={},
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='ac_no',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='gl_no',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='virtualcard',
            constraint=models.UniqueConstraint(fields=('gl_no', 'ac_no'), name='uniq_virtual_card_gl_ac'),
        ),
    ]
