# Generated by Django 5.2.7 on 2025-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_alter_virtualcard_options_alter_virtualcard_ac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
