# Generated by Django 5.2.8 on 2025-12-03 18:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_admin', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('ac_no', models.CharField(max_length=50)),
                ('asset_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('asset_serial_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('asset_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_purchase', models.DateField()),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('asset_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('asset_life_months', models.PositiveIntegerField()),
                ('minimum_asset_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depreciation_frequency', models.CharField(choices=[('12', 'Monthly'), ('4', 'Quarterly'), ('2', 'Semi-Annually'), ('1', 'Annually')], default='12', max_length=10)),
                ('total_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_disposed', models.BooleanField(default=False)),
                ('fixed_asset_profit_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fixed_asset_loss_ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('allowance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowance_accounts', to='accounts_admin.account')),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetclass')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetgroup')),
                ('asset_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetlocation')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assettype')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts_admin.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.department')),
                ('depreciation_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.depreciationmethod')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_accounts', to='accounts_admin.account')),
                ('fixed_asset_loss_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_gl', to='accounts_admin.account')),
                ('fixed_asset_profit_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_gl', to='accounts_admin.account')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_accounts', to='accounts_admin.account')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.officer')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fixed_assets.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_residual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('new_residual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('revaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='fixed_assets.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('disposal_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disposal_reason', models.TextField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='fixed_assets.fixedasset')),
            ],
        ),
    ]
