# Generated by Django 5.1.4 on 2025-03-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(max_length=50, unique=True)),
                ('gl_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('ac_no', models.CharField(max_length=50)),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('asset_serial_no', models.CharField(max_length=100, unique=True)),
                ('asset_model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_purchase', models.DateField()),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('asset_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('asset_life_months', models.PositiveIntegerField()),
                ('minimum_asset_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allowance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_accounts', to='fixed_assets.account')),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.assetclass')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.assetgroup')),
                ('asset_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.assetlocation')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.assettype')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='fixed_assets.account')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.department')),
                ('depreciation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.depreciationmethod')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_accounts', to='fixed_assets.account')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='fixed_assets.account')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.officer')),
            ],
        ),
    ]
