# Generated by Django 5.1.4 on 2025-03-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='allowance_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts_admin.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
