# Generated by Django 5.1.4 on 2025-03-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0002_alter_fixedasset_gl_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='asset_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
