# Generated by Django 5.1.4 on 2025-03-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('fixed_assets', '0003_fixedasset_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='allowance_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowance_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetclass'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetgroup'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assetlocation'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.assettype'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.department'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.depreciationmethod'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_accounts', to='accounts_admin.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.officer'),
        ),
    ]
