# Generated by Django 5.1.4 on 2025-03-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0004_alter_fixedasset_allowance_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_frequency',
            field=models.CharField(choices=[('12', 'Monthly'), ('4', 'Quarterly'), ('2', 'Semi-Annually'), ('1', 'Annually')], default='12', max_length=10),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='numerical_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fixed_assets.fixedasset')),
            ],
        ),
    ]
