# Generated by Django 5.1.4 on 2025-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0005_fixedasset_depreciation_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='numerical_value',
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_serial_no',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
