# Generated by Django 5.1.4 on 2025-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0006_remove_fixedasset_numerical_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='total_depreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
