# Generated by Django 5.1.4 on 2025-03-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
        ('fixed_assets', '0007_fixedasset_total_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.branch'),
        ),
    ]
