# Generated by Django 5.1.4 on 2025-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0008_alter_fixedasset_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
