# Generated by Django 5.1.4 on 2025-03-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0009_fixedasset_net_book_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='net_book_value',
        ),
    ]
