# Generated by Django 5.1.4 on 2025-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0010_remove_fixedasset_net_book_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
