# Generated by Django 5.1.4 on 2025-03-11 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0011_alter_assettransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('disposal_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disposal_reason', models.TextField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='fixed_assets.fixedasset')),
            ],
        ),
    ]
