# Generated by Django 5.1.4 on 2025-03-14 11:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0012_fixedasset_is_disposed_assetdisposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_residual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('new_residual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('revaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='fixed_assets.fixedasset')),
            ],
        ),
    ]
