# Generated by Django 5.1.4 on 2025-03-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
        ('fixed_assets', '0013_assetrevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='fixed_asset_loss_ac_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='fixed_asset_loss_gl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_gl', to='accounts_admin.account'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='fixed_asset_profit_ac_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='fixed_asset_profit_gl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_gl', to='accounts_admin.account'),
        ),
    ]
