# Generated by Django 5.1.4 on 2026-01-13 21:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
        ('fixed_assets', '0015_assetclass_uuid_assetdisposal_uuid_assetgroup_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetImpairment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('impairment_date', models.DateField(default=django.utils.timezone.now)),
                ('previous_nbv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impairment_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_nbv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impairments', to='fixed_assets.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_number', models.CharField(max_length=100)),
                ('insurance_company', models.CharField(max_length=200)),
                ('coverage_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('fire', 'Fire'), ('theft', 'Theft'), ('all_risk', 'All Risk'), ('other', 'Other')], max_length=100)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='asset_insurance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='fixed_assets.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('emergency', 'Emergency Repair'), ('upgrade', 'Upgrade/Enhancement'), ('inspection', 'Inspection'), ('calibration', 'Calibration')], max_length=50)),
                ('maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='asset_maintenance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fixed_assets.fixedasset')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_document', models.FileField(blank=True, null=True, upload_to='asset_transfers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fixed_assets.fixedasset')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='company.branch')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='fixed_assets.department')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='fixed_assets.assetlocation')),
                ('from_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='fixed_assets.officer')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='company.branch')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='fixed_assets.department')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='fixed_assets.assetlocation')),
                ('to_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='fixed_assets.officer')),
            ],
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_date', models.DateField()),
                ('verified_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('verified', 'Verified - Asset Found'), ('not_found', 'Not Found'), ('damaged', 'Found - Damaged'), ('relocated', 'Found - Different Location')], max_length=20)),
                ('physical_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unusable', 'Unusable')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_verification/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixed_assets.assetlocation')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='fixed_assets.fixedasset')),
            ],
            options={
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('warranty_provider', models.CharField(max_length=200)),
                ('warranty_type', models.CharField(choices=[('manufacturer', 'Manufacturer Warranty'), ('extended', 'Extended Warranty'), ('service', 'Service Contract'), ('parts', 'Parts Warranty')], max_length=50)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('coverage_details', models.TextField()),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warranty_document', models.FileField(blank=True, null=True, upload_to='asset_warranty/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='fixed_assets.fixedasset')),
            ],
        ),
    ]
