# Generated by Django 5.2.8 on 2025-12-03 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=100)),
                ('contact_phone_no', models.CharField(max_length=100)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('system_date_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('license_key', models.CharField(max_length=50)),
                ('session_status', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('float_account_number', models.CharField(blank=True, help_text='The 9PSB wallet or float account number assigned to this company.', max_length=25, null=True)),
                ('last_notification_date', models.DateField(blank=True, null=True)),
                ('float_gl_no', models.CharField(blank=True, help_text="GL number linked to the company's float account.", max_length=25, null=True)),
                ('float_ac_no', models.CharField(blank=True, help_text='Internal ledger account number linked to the float account.', max_length=25, null=True)),
                ('mobile_teller_gl_no', models.CharField(blank=True, help_text="GL number linked to the company's Mobile Teller account.", max_length=25, null=True)),
                ('mobile_teller_ac_no', models.CharField(blank=True, help_text='Internal ledger account number linked to the Mobile Teller account.', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(help_text='Branch ID from vendor database', max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=6)),
                ('branch_name', models.CharField(max_length=90)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branch_logos/')),
                ('address', models.TextField()),
                ('cac_number', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=50)),
                ('bvn_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('head_office', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Professional', 'Professional'), ('Ultimate', 'Ultimate'), ('Enterprise', 'Enterprise')], default='Starter', max_length=15)),
                ('session_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('system_date_date', models.DateField(blank=True, null=True)),
                ('session_status', models.CharField(blank=True, max_length=10, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company')),
            ],
        ),
    ]
