# Generated by Django 5.1.4 on 2025-01-16 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(max_length=6)),
                ('branch_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=100)),
                ('contact_phone_no', models.CharField(max_length=100)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('system_date_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('license_key', models.CharField(max_length=50)),
                ('session_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=6, unique=True)),
                ('branch_name', models.CharField(max_length=90)),
                ('session_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('system_date_date', models.DateField(blank=True, null=True)),
                ('session_status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company')),
            ],
        ),
    ]
