# Generated by Django 5.1.4 on 2025-01-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='branch_name',
        ),
    ]
