# Generated by Django 5.1.4 on 2025-01-16 09:49
# NOTE: Operations emptied because 0001_initial was regenerated without these fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        # Fields already removed in regenerated 0001_initial
    ]
