# Generated by Django 5.1.4 on 2025-01-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
