# Generated by Django 5.1.4 on 2025-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Professional', 'Professional'), ('Ultimate', 'Ultimate'), ('Enterprise', 'Enterprise')], default='Starter', max_length=15),
        ),
    ]
