# Generated by Django 5.1.4 on 2025-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
