# Generated by Django 5.1.4 on 2025-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
