# Generated by Django 5.1.4 on 2025-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_branch_company_name_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
