# Generated by Django 5.1.4 on 2025-04-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_branch_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
