# Generated by Django 5.1.4 on 2025-04-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_branch_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
