# Generated by Django 5.1.4 on 2025-04-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_branch_phone_number_branch_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
