# Generated by Django 5.1.4 on 2025-04-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_smsdelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsdelivery',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='smsdelivery',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch'),
        ),
        migrations.AlterField(
            model_name='smsdelivery',
            name='message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smsdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
