# Generated by Django 5.1.4 on 2025-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='head_office',
            field=models.BooleanField(default=False),
        ),
    ]
