# Generated by Django 5.1.4 on 2025-09-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_branch_head_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
    ]
