# Generated by Django 5.2.7 on 2025-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_remove_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='float_account_number',
            field=models.CharField(blank=True, help_text='The 9PSB wallet or float account number assigned to this company.', max_length=20, null=True),
        ),
    ]
