# Generated by Django 5.2.7 on 2025-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_float_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='float_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the float account.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='float_gl_no',
            field=models.CharField(blank=True, help_text='GL number linked to the company’s float account.', max_length=20, null=True),
        ),
    ]
