# Generated by Django 5.2.7 on 2025-11-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_company_float_ac_no_company_float_gl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile_teller_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the Mobile Teller account.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_teller_gl_no',
            field=models.CharField(blank=True, help_text='GL number linked to the company’s Mobile Teller account.', max_length=20, null=True),
        ),
    ]
