# Generated by Django 5.1.4 on 2026-01-12 23:28

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    import uuid as uuid_module
    for model_name in ['Branch', 'Company', 'SmsDelivery']:
        Model = apps.get_model('company', model_name)
        for obj in Model.objects.all():
            obj.uuid = uuid_module.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_mobile_teller_ac_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdelivery',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='smsdelivery',
            name='branch_id',
            field=models.CharField(help_text='Branch ID from vendor database', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='smsdelivery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='branch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='smsdelivery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='float_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the float account.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='float_account_number',
            field=models.CharField(blank=True, help_text='The 9PSB wallet or float account number assigned to this company.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='float_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's float account.", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_teller_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the Mobile Teller account.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_teller_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's Mobile Teller account.", max_length=25, null=True),
        ),
    ]
