# Generated by Django 5.2.8 on 2025-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_company_mobile_teller_ac_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdelivery',
            name='branch',
        ),
        migrations.AddField(
            model_name='smsdelivery',
            name='branch_id',
            field=models.CharField(help_text='Branch ID from vendor database', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='float_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's float account.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_teller_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's Mobile Teller account.", max_length=20, null=True),
        ),
    ]
