# Generated by Django 5.1.4 on 2026-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_remove_smsdelivery_branch_branch_uuid_company_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate branch when subscription is not made'),
        ),
    ]
