# Generated by Django 5.2.8 on 2025-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_remove_smsdelivery_branch_smsdelivery_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='session_status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
