# Generated by Django 5.2.8 on 2025-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_alter_company_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='float_account_number',
            field=models.CharField(blank=True, help_text='The 9PSB wallet or float account number assigned to this company.', max_length=25, null=True),
        ),
    ]
