# Generated by Django 5.1.4 on 2026-01-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_vendoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='max_customers',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of customers this branch can create. 0 = unlimited.'),
        ),
    ]
