# Generated by Django 5.2.8 on 2025-11-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_alter_company_float_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='float_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the float account.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='float_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's float account.", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_teller_ac_no',
            field=models.CharField(blank=True, help_text='Internal ledger account number linked to the Mobile Teller account.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_teller_gl_no',
            field=models.CharField(blank=True, help_text="GL number linked to the company's Mobile Teller account.", max_length=25, null=True),
        ),
    ]
