# Generated by Django 5.1.4 on 2026-01-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_branch_max_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='can_fixed_assets',
            field=models.BooleanField(default=True, help_text='Enable Fixed Assets feature for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='can_fixed_deposit',
            field=models.BooleanField(default=True, help_text='Enable Fixed Deposit feature for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='can_loans',
            field=models.BooleanField(default=True, help_text='Enable Loans feature for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='can_mobile_banking',
            field=models.BooleanField(default=False, help_text='Enable Mobile Banking feature for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='can_sms_alerts',
            field=models.BooleanField(default=False, help_text='Enable SMS Alerts feature for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='can_transfers',
            field=models.BooleanField(default=True, help_text='Enable Fund Transfers feature for this branch'),
        ),
    ]
