# Generated by Django 5.2.7 on 2026-01-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_parent_branch',
            field=models.BooleanField(default=False, help_text='Only admin users from parent branch can create/edit chart of accounts'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendoruser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
