# Generated by Django 5.2.7 on 2025-11-21 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('high_value_transactions', models.PositiveIntegerField(default=0)),
                ('authentication_actions', models.PositiveIntegerField(default=0)),
                ('customer_actions', models.PositiveIntegerField(default=0)),
                ('transaction_actions', models.PositiveIntegerField(default=0)),
                ('report_actions', models.PositiveIntegerField(default=0)),
                ('admin_actions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Statistics',
                'verbose_name_plural': 'Audit Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_authentication', models.BooleanField(default=True)),
                ('track_customer_operations', models.BooleanField(default=True)),
                ('track_account_operations', models.BooleanField(default=True)),
                ('track_transactions', models.BooleanField(default=True)),
                ('track_loans', models.BooleanField(default=True)),
                ('track_reports', models.BooleanField(default=True)),
                ('track_admin_operations', models.BooleanField(default=True)),
                ('track_fixed_assets', models.BooleanField(default=True)),
                ('track_cbn_returns', models.BooleanField(default=True)),
                ('track_view_actions', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=2555)),
                ('auto_cleanup_enabled', models.BooleanField(default=True)),
                ('enable_real_time_alerts', models.BooleanField(default=True)),
                ('alert_on_failed_logins', models.BooleanField(default=True)),
                ('alert_on_high_value_transactions', models.BooleanField(default=True)),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('log_ip_addresses', models.BooleanField(default=True)),
                ('log_user_agents', models.BooleanField(default=True)),
                ('encrypt_sensitive_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Configuration',
                'verbose_name_plural': 'Audit Configurations',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('TRANSACTION', 'Transaction')], max_length=20)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('CUSTOMER', 'Customer Management'), ('ACCOUNT', 'Account Management'), ('TRANSACTION', 'Transactions'), ('LOAN', 'Loan Management'), ('REPORT', 'Reports'), ('ADMIN', 'Administration'), ('FIXED_ASSETS', 'Fixed Assets'), ('FIXED_DEPOSIT', 'Fixed Deposits'), ('CBN_RETURNS', 'CBN Returns'), ('SETTINGS', 'Settings'), ('BULK_OPS', 'Bulk Operations')], max_length=20)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('compliance_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SECURITY', 'Security Alert'), ('COMPLIANCE', 'Compliance Alert'), ('PERFORMANCE', 'Performance Alert'), ('ERROR', 'Error Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('audit_trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='audit_trail.audittrail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['timestamp', 'user'], name='audit_trail_timesta_78bd18_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', 'category'], name='audit_trail_action_8e2c67_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['account_number'], name='audit_trail_account_b348d8_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['customer_id'], name='audit_trail_custome_857353_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['transaction_reference'], name='audit_trail_transac_ad4626_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['compliance_level'], name='audit_trail_complia_f584b8_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['ip_address'], name='audit_trail_ip_addr_ab7887_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['alert_type', 'severity'], name='audit_trail_alert_t_979bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['is_resolved'], name='audit_trail_is_reso_6743ed_idx'),
        ),
    ]
