# Generated by Django 5.1.4 on 2025-04-08 18:18

import audit_trail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='after',
            field=models.JSONField(blank=True, encoder=audit_trail.models.CustomJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before',
            field=models.JSONField(blank=True, encoder=audit_trail.models.CustomJSONEncoder, null=True),
        ),
    ]
