# Generated by Django 5.1.4 on 2026-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0002_auditalert_uuid_auditconfiguration_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='branch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Branch ID from vendor database', max_length=20, null=True),
        ),
    ]
