# Generated by Django 5.1.4 on 2025-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0003_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
