# Generated by Django 5.1.4 on 2025-04-08 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0005_alter_auditlog_options_alter_auditlog_action_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_trail_timesta_65028d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_trail_user_id_3c17e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_trail_action_6d962f_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='System Generated'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_branch',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='User Branch'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'user'], name='audit_trail_timesta_4b93df_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_role', 'timestamp'], name='audit_trail_user_ro_a7bb06_idx'),
        ),
    ]
