# Generated by Django 5.1.4 on 2025-01-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Id_card_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_no', models.CharField(max_length=6, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debit_account', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.BigIntegerField(help_text='Maximum days of arrears')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_name', models.CharField(max_length=80, unique=True)),
                ('gl_no', models.CharField(max_length=10, unique=True)),
                ('account_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Assets'), (2, 'Liabilities'), (3, 'Equity'), (4, 'Expenses'), (5, 'Income')], default='1')),
                ('currency', models.PositiveIntegerField(blank=True, choices=[(1, 'Us dollar'), (2, 'Nigeria')], default='1')),
                ('double_entry_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Debit & Credit'), (2, 'Credit'), (3, 'Debit')], default='1')),
                ('is_non_financial', models.BooleanField(default=False)),
                ('interest_gl', models.CharField(blank=True, max_length=6, null=True)),
                ('interest_ac', models.CharField(blank=True, max_length=6, null=True)),
                ('sys_narat', models.CharField(blank=True, max_length=6, null=True)),
                ('pen_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('pen_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('prov_cr_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('prov_cr_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('prov_dr_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('prov_dr_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('writ_off_dr_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('writ_off_dr_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('writ_off_cr_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('writ_off_cr_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_com_gl_no', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_com_ac_no', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_com_fee_rate', models.CharField(blank=True, max_length=3, null=True)),
                ('loan_proc_fee_rate', models.CharField(blank=True, max_length=3, null=True)),
                ('loan_appl_fee_rate', models.CharField(blank=True, max_length=3, null=True)),
                ('loan_commit_fee_rate', models.CharField(blank=True, max_length=3, null=True)),
                ('int_to_recev_gl_dr', models.CharField(blank=True, max_length=6, null=True)),
                ('int_to_recev_ac_dr', models.CharField(blank=True, max_length=6, null=True)),
                ('unearned_int_inc_gl', models.CharField(blank=True, max_length=6, null=True)),
                ('unearned_int_inc_ac', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_com_gl_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_com_ac_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_proc_gl_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_proc_ac_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_appl_gl_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_appl_ac_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_commit_gl_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('loan_commit_ac_vat', models.CharField(blank=True, max_length=6, null=True)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_admin.account')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_admin.region')),
            ],
        ),
    ]
