# Generated by Django 5.1.4 on 2025-01-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0001_initial'),
        ('company', '0004_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Assets'), (2, 'Liabilities'), (3, 'Equity'), (4, 'Expenses'), (5, 'Income')], default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Us dollar'), (2, 'Nigeria')], default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='double_entry_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Debit & Credit'), (2, 'Credit'), (3, 'Debit')], default=1),
        ),
    ]
