# Generated by Django 5.1.4 on 2025-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0002_account_branch_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gl_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gl_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
