# Generated by Django 5.1.4 on 2025-01-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0003_alter_account_gl_name_alter_account_gl_no'),
        ('company', '0004_alter_branch_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_officer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_Officer', to='company.branch'),
        ),
        migrations.AddField(
            model_name='business_sector',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_Sector', to='company.branch'),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='company.branch'),
        ),
        migrations.AddField(
            model_name='id_card_type',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_card_type', to='company.branch'),
        ),
        migrations.AddField(
            model_name='interestrate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interestRate', to='company.branch'),
        ),
        migrations.AddField(
            model_name='loanprovision',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanProvision', to='company.branch'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='company.branch'),
        ),
        migrations.AddField(
            model_name='region',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='company.branch'),
        ),
    ]
