# Generated by Django 5.1.4 on 2025-01-18 10:21
# NOTE: Operations emptied because 0001_initial was regenerated without InterestRate model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0004_account_officer_branch_business_sector_branch_and_more'),
    ]

    operations = [
        # InterestRate model already removed in regenerated 0001_initial
    ]
