# Generated by Django 5.1.4 on 2025-01-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_card_type',
            name='id_card_name',
            field=models.CharField(max_length=30),
        ),
    ]
