# Generated by Django 5.1.4 on 2025-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0007_alter_id_card_type_id_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fixed_dep_int_ac_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='fixed_dep_int_gl_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
