# Generated by Django 5.1.4 on 2025-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0008_account_fixed_dep_int_ac_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gl_name',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='gl_no',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
