# Generated by Django 5.1.4 on 2026-01-13 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0010_account_uuid_account_officer_uuid_and_more'),
        ('company', '0028_branch_max_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Custom display name (leave blank to use GL Name)', max_length=100, null=True)),
                ('usage_type', models.CharField(choices=[('customer', 'New Customer Account'), ('additional', 'Additional Customer Account'), ('both', 'Both New & Additional')], default='both', help_text='Where this account type should appear', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Select account from Chart of Accounts', on_delete=django.db.models.deletion.CASCADE, related_name='customer_account_type_settings', to='accounts_admin.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account_types', to='company.branch')),
            ],
            options={
                'verbose_name': 'Customer Account Type',
                'verbose_name_plural': 'Customer Account Types',
                'ordering': ['sort_order', 'account__gl_name'],
                'unique_together': {('branch', 'account')},
            },
        ),
    ]
