# Generated by Django 5.2.7 on 2026-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0011_add_customer_account_type'),
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('branch', 'region_name')},
        ),
    ]
