# Generated by Django 5.2.7 on 2026-01-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0012_remove_region_unique_add_unique_together'),
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gl_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='gl_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('branch', 'gl_name'), ('branch', 'gl_no')},
        ),
    ]
