# Generated by Django 5.1.4 on 2026-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0013_account_unique_per_branch'),
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_sector',
            name='sector_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='business_sector',
            unique_together={('branch', 'sector_name')},
        ),
    ]
