# Generated by Django 5.2.7 on 2026-01-21 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0014_alter_business_sector_sector_name_and_more'),
        ('company', '0029_branch_can_fixed_assets_branch_can_fixed_deposit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['gl_no']},
        ),
        migrations.AlterField(
            model_name='account_officer',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='account_officer',
            unique_together={('branch', 'user')},
        ),
        migrations.CreateModel(
            name='LoanAutoRepaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_auto_repayment_enabled', models.BooleanField(default=False, help_text='Enable automatic loan repayment calculation on session close')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Select loan account from Chart of Accounts', on_delete=django.db.models.deletion.CASCADE, related_name='loan_auto_repayment_settings', to='accounts_admin.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_auto_repayment_settings', to='company.branch')),
            ],
            options={
                'verbose_name': 'Loan Auto Repayment Setting',
                'verbose_name_plural': 'Loan Auto Repayment Settings',
                'ordering': ['account__gl_no'],
                'unique_together': {('branch', 'account')},
            },
        ),
    ]
