# Generated by Django 5.1.4 on 2026-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_admin', '0015_loan_auto_repayment_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanautorepaymentsetting',
            name='interest_income_gl_no',
            field=models.CharField(blank=True, help_text='GL number where interest income will be credited (e.g., 40101)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanautorepaymentsetting',
            name='int_receivable_gl_no',
            field=models.CharField(blank=True, help_text='Interest Receivable GL to debit (reduces balance sheet asset)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanautorepaymentsetting',
            name='unearned_int_income_gl_no',
            field=models.CharField(blank=True, help_text='Unearned Interest Income GL to credit (reduces balance sheet liability)', max_length=10, null=True),
        ),
    ]
