# Generated by Django 5.1.4 on 2026-01-12 23:28

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    import uuid as uuid_module
    Model = apps.get_model('ninepsb', 'PsbBank')
    for obj in Model.objects.all():
        obj.uuid = uuid_module.uuid4()
        obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('ninepsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psbbank',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='psbbank',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
