# Generated by Django 5.2.7 on 2026-01-30 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninepsb', '0002_psbbank_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('transfer', 'Transfer/Inflow'), ('account-upgrade', 'Account Upgrade')], max_length=30)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('transaction_ref', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sender_account', models.CharField(blank=True, max_length=20, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('verified', 'Verified')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_response', models.JSONField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Notification',
                'verbose_name_plural': 'Webhook Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'account_number'], name='ninepsb_web_session_32b649_idx'), models.Index(fields=['status', 'created_at'], name='ninepsb_web_status_ad16b5_idx')],
            },
        ),
    ]
